### PR TITLE
filename seperator setting to fix #54

### LINKED ISSUE #54: Private skin for players with underscore in the name does not work
Seems players with underscore in their name cannot find their skins

Repro:

- Have a playername `first_second`
- name the skin `player_first_second_0.png`
- log in as that player and search your private skin
=> Skin is not in the list
- login as admin and search the skin in the list
=> Skin is there, selectable, but says it is called `second 0`

### PR DESCRIPTION
**Pull request by blaboing**
Adds a filename split seperator setting that lets you choose between old style `_` and `.` because dot is the only char that isn´t allowed in playername but in texturenames.
Default value is `_` to keep it compatible with older versions, while `.` offers a solution to fix #54.

### CODE REVIEW

**Comment by ronoaldo** [comment]
This looks good. I'll test it out!

File: skinlist.lua [hunk 1]
```diff
@@ -2,7 +2,7 @@ local skins_dir_list = minetest.get_dir_list(skins.modpath.."/textures")
 
 for _, fn in pairs(skins_dir_list) do
 	local name, sort_id, is_preview, playername
-	local nameparts = string.gsub(fn, "[.]", "_"):split("_")
+	local nameparts = string.gsub(fn, "[.]", skins.fsep):split(skins.fsep)
```
Comment (SmallJoker) [inline skinlist.lua:5]: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3625

```Lua
local nameparts = string.gsub(fn, "[.]", "_"):split("_", 1)
```

should also fix the issue without a workaround like this, right?

Comment (blaboing) [reply skinlist.lua:5]: Could you explain the idea behind it? Because I gave it a try and didn't get any different result.

Comment (SmallJoker) [reply skinlist.lua:5]: That particular code splits `player_User_name` into `{ "player", "User_name" }` to properly separate the "player"/"character" part from the file name. I now see that the file extension would have to be split manually (either before this line or using index 2).

My idea is basically to provide a workaround for this issue without introducing a new format.

Comment (blaboing) [reply skinlist.lua:5]: > That particular code splits `player_User_name` into `{ "player", "User_name" }` to properly separate the "player"/"character" part from the file name.

Yep it splits into more than that.
```lua
filename = "playerORcharacter_accountname_skinnumberORname_optionalpreview.png"
local nameparts = string.gsub(filename, "[.]", "_"):split("_")
-- { [1] = playerORcharacter,[2] = accountname,[3] = skinnumberORname,[4] = optionalpreview,[5] = png,} 
```

>I now see that the file extension would have to be split manually (either before this line or using index 2).

File extension is already handled before splitting by replacing `.` with `_`.
```lua
string.gsub(fn, "[.]", "_")
```

**Review by SmallJoker — APPROVED** [review]
LGTM. Will merge in a few days unless there's objections.
